-- 테이블명 별칭은 SELECT절에서도 바로 적용, FROM - WHERE - GROUP BY - HAVING - SELECT - ORDER BY 순서로 실행되므로
SELECT APNT_NO, PT_NAME, AP.PT_NO, AP.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP
         INNER JOIN  PATIENT PT ON AP.PT_NO = PT.PT_NO
         INNER JOIN DOCTOR DR ON AP.MDDR_ID = DR.DR_ID
WHERE DATE(APNT_YMD) ='2022-04-13' AND APNT_CNCL_YN = 'N' AND AP.MCDP_CD='CS'
ORDER BY APNT_YMD;